CINIC-10:
  num_hidden_layers: 5
  hidden_dim: 512
  output_feature_size: 512
  lr: 0.01
  epoch: 100
  k: 9
  k_neig: 5
  vision: CLIP_ViT-L_14@336          # DeiT-B_16@384  ViT-G_14   CLIP_ViT-L_14@336
  language: All-Roberta-large-v1    #all-mpnet-base-v2    All-Roberta-large-v1


CIFAR-10:
  num_hidden_layers: 5
  hidden_dim: 512
  output_feature_size: 512
  lr: 0.01
  epoch: 100
  k: 9
  k_neig: 5    # 5~10
  vision: ViT-G_14                # DeiT-B_16@384  ViT-G_14   CLIP_ViT-L_14@336
  language: All-Roberta-large-v1  # all-mpnet-base-v2   All-Roberta-large-v1   


CIFAR-100:
  num_hidden_layers: 3 #5
  hidden_dim: 512
  output_feature_size: 512
  lr: 0.01
  epoch: 100
  k: 90
  k_neig: 20
  vision: CLIP_ViT-L_14@336     # DeiT-B_16@384  ViT-G_14   CLIP_ViT-L_14@336
  language: All-Roberta-large-v1 # all-mpnet-base-v2   All-Roberta-large-v1   



Imagenet-100:
  num_hidden_layers: 5
  hidden_dim: 512
  output_feature_size: 512
  lr: 0.01
  epoch: 100
  k: 90
  k_neig: 20
  vision: ViT-G_14            # DeiT-B_16@384  ViT-G_14   CLIP_ViT-L_14@336
  language: all-mpnet-base-v2 # all-mpnet-base-v2   All-Roberta-large-v1    


language_models:
  - all-MiniLM-L6-v1
  - all-MiniLM-L6-v2
  - all-MiniLM-L12-v1
  - all-MiniLM-L12-v2
  - msmarco-distilbert-dot-v5
  - average_word_embeddings_komninos
  - all-distilroberta-v1
  - msmarco-bert-base-dot-v5
  - all-mpnet-base-v2
  - all-mpnet-base-v1
  - gtr-t5-base
  - sentence-t5-base
  - average_word_embeddings_glove.6B.300d
  - gtr-t5-large
  - sentence-t5-large
  - All-Roberta-large-v1
  - gtr-t5-xl
  - sentence-t5-xl
  - RN50
  - RN101
  - RN50x4
  - RN50x16
  - RN50x64
  - ViT-B_32
  - ViT-B_16
  - ViT-L_14
  - ViT-L_14@336px


vision_models:
  - CLIP_RN50
  - CLIP_RN101
  - CLIP_RN50x4
  - CLIP_RN50x16
  - CLIP_RN50x64
  - CLIP_ViT-B_32
  - CLIP_ViT-B_16
  - CLIP_ViT-L_14
  - CLIP_ViT-L_14@336
  - CN-B-1
  - CN-B-22
  - CN-L-1
  - CN-L-22
  - CN-L-22ft@384
  - CN-XL-22ft@384
  - DeiT-T_16
  - DeiT-T_16d
  - DeiT-S_16
  - DeiT-S_16d
  - DeiT-B_16
  - DeiT-B_16@384
  - DeiT-B_16d
  - DeiT-B_16d@384
  - RN50
  - ViT-S_16
  - ViT-S_8
  - ViT-B_16
  - ViT-B_8
  - ViT-S_14
  - ViT-B_14
  - ViT-L_14
  - ViT-G_14
